const { chromium } = require('playwright');
const http = require('http'); const fs = require('fs');
const html = fs.readFileSync('huitong.html','utf8');
const page = '<!doctype html><html><head><meta charset="utf-8"></head><body>'+html+'</body></html>';
const srv = http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(page);});
srv.listen(0, async ()=>{
  const port = srv.address().port;
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const p = await b.newPage({ viewport:{width:1200,height:1200} });
  const errs=[]; p.on('pageerror',e=>errs.push('PAGEERR '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('CON '+m.text());});
  await p.goto('http://localhost:'+port+'/');
  await p.waitForTimeout(700);
  await p.locator('nav.tabs button[data-tab="t-read"]').click(); await p.waitForTimeout(200);
  await p.locator('.reson[data-k="self"] button[data-v="y"]').first().click();
  await p.locator('.reson[data-k="career"] button[data-v="n"]').first().click();
  await p.waitForTimeout(150);
  await p.locator('nav.tabs button[data-tab="t-guide"]').click(); await p.waitForTimeout(200);
  await p.locator('#deep-notes').fill('测试笔记：核心自我很准，事业方向存疑，下步验证A项目。'); await p.waitForTimeout(150);
  await p.locator('nav.tabs button[data-tab="t-vault"]').click(); await p.waitForTimeout(150);
  await p.locator('#prof-name').fill('张三·测试盘');
  await p.locator('#v-save').click(); await p.waitForTimeout(200);
  console.log('保存后:', JSON.stringify(await p.evaluate(()=>({count:VAULT.length,name:VAULT[0].name,notes:VAULT[0].notes,fb:VAULT[0].feedback,ls:!!localStorage.getItem('huitong-vault')}))));
  await p.locator('nav.tabs button[data-tab="t-cast"]').click();
  await p.locator('#f-y').fill('1985'); await p.locator('#f-m').fill('3'); await p.locator('#f-d').fill('20');
  await p.locator('#form button[type="submit"]').click(); await p.waitForTimeout(300);
  console.log('切换新盘:', JSON.stringify(await p.evaluate(()=>({y:STATE.input.y,notes:NOTES}))));
  await p.locator('nav.tabs button[data-tab="t-vault"]').click(); await p.waitForTimeout(150);
  await p.locator('[data-load]').first().click(); await p.waitForTimeout(300);
  console.log('载入接力:', JSON.stringify(await p.evaluate(()=>({y:STATE.input.y,fbSelf:FB.self,fbCareer:FB.career,notes:NOTES,tab:document.querySelector('section.tab.active').id}))));
  await p.locator('nav.tabs button[data-tab="t-vault"]').click();
  await p.locator('#io-export').click(); await p.waitForTimeout(150);
  console.log('导出JSON长度:', await p.evaluate(()=>document.getElementById('io-box').value.length));
  await p.reload(); await p.waitForTimeout(700);
  console.log('刷新后持久化:', JSON.stringify(await p.evaluate(()=>({count:VAULT.length,name:(VAULT[0]||{}).name}))));
  console.log(errs.length?'ERRORS:\n'+errs.join('\n'):'NO JS ERRORS');
  await b.close(); srv.close();
});
